### PR TITLE
added to .gitignore

### PR DESCRIPTION
**Pull request by sorenrichenberg**

### CODE REVIEW

**Comment by sorenrichenberg** [comment]
Yes

**Comment by 707ryanmckay707** [comment]
Looks great!

**Comment by 707ryanmckay707** [comment]
> Yes

Y ES

**Review by 707ryanmckay707 — APPROVED** [review]
Yes

**Comment by OwenMastropietro** [comment]
Hey Soren, thank you for this contribution! I approve this contribution as it is in alignment with our greater goals.

**Review by OwenMastropietro — APPROVED** [review]

**Review by sorenrichenberg — COMMENTED** [review]
Yes

**Pull request merged**
